services:
  shoes-api:
    build: 
      dockerfile: shoes_store.img.dev
    ports:
      - 8000:${SHOES_STORE_PORT}
    volumes:
      - ./:/app:rw
    networks:
      - shoes-store-network

networks:
  shoes-store-network: {}
volumes:
  shoes-store-volume:
