FROM python:3.12.2-alpine3.19

WORKDIR /app
COPY . .

RUN pip3 install virtualenv && \
    python3 -m venv .venv && \
    pip3 install poetry && \
    poetry install

RUN chmod +x .

CMD ["/bin/sh", ".command/run"]
